[profile.default]
src = "src"
out = "out"
libs = ["lib"]
runs = 300
[profile.invariants]
runs = 300
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options